// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-MQyjDKIUY2WIMIpnB0U-dHQLkmQ-W8',
    appId: '1:679056722256:web:4e3c06e7a57b17ecf34455',
    messagingSenderId: '679056722256',
    projectId: 'el-wedding',
    authDomain: 'el-wedding.firebaseapp.com',
    storageBucket: 'el-wedding.appspot.com',
    measurementId: 'G-5MVLXDWBYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqFU_eXgNoddBn2wsCJRk3gDiQcXvTq_I',
    appId: '1:679056722256:android:2275f0d1fe74ae2af34455',
    messagingSenderId: '679056722256',
    projectId: 'el-wedding',
    storageBucket: 'el-wedding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCYsvObOe7mBJOz7alqAG1FopVdeCHzBs',
    appId: '1:679056722256:ios:e5dc92bf5749a213f34455',
    messagingSenderId: '679056722256',
    projectId: 'el-wedding',
    storageBucket: 'el-wedding.appspot.com',
    iosBundleId: 'com.example.elWedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCYsvObOe7mBJOz7alqAG1FopVdeCHzBs',
    appId: '1:679056722256:ios:e5dc92bf5749a213f34455',
    messagingSenderId: '679056722256',
    projectId: 'el-wedding',
    storageBucket: 'el-wedding.appspot.com',
    iosBundleId: 'com.example.elWedding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx-MQyjDKIUY2WIMIpnB0U-dHQLkmQ-W8',
    appId: '1:679056722256:web:8c30508d3e3dc5b3f34455',
    messagingSenderId: '679056722256',
    projectId: 'el-wedding',
    authDomain: 'el-wedding.firebaseapp.com',
    storageBucket: 'el-wedding.appspot.com',
    measurementId: 'G-6DEV9C9WBG',
  );
}
